// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $exercise from "./routes/exercise.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $sleep from "./routes/sleep.tsx";
import * as $study from "./routes/study.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ExerciseForm from "./islands/ExerciseForm.tsx";
import * as $ExerciseHeatmapSection from "./islands/ExerciseHeatmapSection.tsx";
import * as $ExerciseList from "./islands/ExerciseList.tsx";
import * as $Heatmap from "./islands/Heatmap.tsx";
import * as $SettingsManager from "./islands/SettingsManager.tsx";
import * as $SleepForm from "./islands/SleepForm.tsx";
import * as $SleepHeatmapSection from "./islands/SleepHeatmapSection.tsx";
import * as $SleepList from "./islands/SleepList.tsx";
import * as $StudyForm from "./islands/StudyForm.tsx";
import * as $StudyHeatmapSection from "./islands/StudyHeatmapSection.tsx";
import * as $StudyList from "./islands/StudyList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/exercise.tsx": $exercise,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/sleep.tsx": $sleep,
    "./routes/study.tsx": $study,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/ExerciseForm.tsx": $ExerciseForm,
    "./islands/ExerciseHeatmapSection.tsx": $ExerciseHeatmapSection,
    "./islands/ExerciseList.tsx": $ExerciseList,
    "./islands/Heatmap.tsx": $Heatmap,
    "./islands/SettingsManager.tsx": $SettingsManager,
    "./islands/SleepForm.tsx": $SleepForm,
    "./islands/SleepHeatmapSection.tsx": $SleepHeatmapSection,
    "./islands/SleepList.tsx": $SleepList,
    "./islands/StudyForm.tsx": $StudyForm,
    "./islands/StudyHeatmapSection.tsx": $StudyHeatmapSection,
    "./islands/StudyList.tsx": $StudyList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
